### PR TITLE
#10 ft(auth): add custom claims

### PR DESCRIPTION
**Pull request by SimonImanigirimpuhwe**
#### What does this PR do?

- Add custom claims

#### Description of Task to be completed? 

- Set query data rules

- Allow user to query only his/her own todo items

#### How should this be manually tested?

- Clone the repo 

- In your home directory  cd this branch `ft-add-custom-claims-#10`

- Then run `npm install` to install all dependencies

- Run `npm start` to start the server

- In your default browser navigate to `http://localhost:3000`

> You should see a login page

> Then log in with google and you should be redirected to the dashboard if successfully logged in

> If you have not added any todo you should see none and then get add some and you will see them get displayed on the interface

#### Any background context you want to provide?

- To login you need to have google account

#### What are the relevant Trello stories?

- [#10](https://trello.com/c/rU88u32R/10-add-custom-claims)

#### Screenshots (if appropriate)
Screen Shot 2020-11-11 at 10 27 59

#### Questions:

- N/A

### CODE REVIEW

**Comment by thepatrickniyo** [comment]
Good work @SimonImanigirimpuhwe! I liked the way you have few changes to review. It made it simple for me to go through codes.

**Comment by SimonImanigirimpuhwe** [comment]
> Good work @SimonImanigirimpuhwe! I liked the way you have few changes to review. It made it simple for me to go through codes.

Great!

**Comment by SamuelSabasNayo** [comment]
Good work!

**Comment by ConstantineMaliza** [comment]
nice work

**Pull request merged**
